SOURCES = foo.c bar.c
TARGET = sample.tns
OBJECTS = $(SOURCES:.c=.o)

CC = nspire-gcc
LD = nspire-ld
OBJCOPY = arm-none-eabi-objcopy
CFLAGS = -Wall -Wextra -O3
LDFLAGS =
ifneq ($(findstring cx8,$(MAKECMDGOALS)),)
	CFLAGS += -D NSP_CX_8BIT
	LIBS = -lSDL-CX8
else
	ifneq ($(findstring cx,$(MAKECMDGOALS)),)
		CFLAGS += -D NSP_CX_16BIT
		LIBS = -lSDL-CX
	else
		LIBS = -lSDL-TC
	endif
endif

cx: all
cx8: all
tc: all
all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $(@:.tns=.elf)
	$(OBJCOPY) -O binary $(@:.tns=.elf) $(TARGET)

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) *.elf $(TARGET)